# Generated by Django 5.2.8 on 2025-12-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('platform', models.CharField(choices=[('NONE', 'NONE'), ('LinkedIn', 'LinkedIn'), ('Indeed', 'Indeed'), ('Jobstreet', 'Jobstreet')], default='NONE', max_length=20)),
                ('job_title', models.CharField(max_length=50)),
                ('job_status', models.CharField(choices=[('NONE', 'NONE'), ('Applied', 'Applied'), ('Interview', 'Interview'), ('Pending Application', 'Pending Application'), ('Hired', 'Hired'), ('Rejected', 'Rejected'), ('Ghosted', 'Ghosted')], default='NONE', max_length=30)),
                ('date_applied', models.DateField()),
                ('job_link', models.CharField(max_length=200)),
            ],
        ),
    ]
