# Generated by Django 5.2.8 on 2025-12-04 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_applied',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
